from pathlib import Path

import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

import export_tflite_model as export_utils
import train_fusion_backbones_small as backbones_pipeline

fusion_pipeline = backbones_pipeline.fusion_pipeline
audio_pipeline = backbones_pipeline.audio_pipeline
imu_pipeline = backbones_pipeline.imu_pipeline
discover_paired_windows = backbones_pipeline.discover_paired_windows
load_imu_window = backbones_pipeline.load_imu_window
load_audio_waveform = backbones_pipeline.load_audio_waveform
get_embedding_model = fusion_pipeline.get_embedding_model

# export_tflite_model.compute_mel_filterbank/compute_hann_window read this as a module
# global, normally set by its own configure_for_model() -- which this script never calls
# since it isn't exporting one of that script's own model variants. The mel/STFT params
# are dataset-level constants, not model-specific, so pointing it at our audio_pipeline
# directly is correct, not a workaround.
export_utils.audio_pipeline = audio_pipeline

EXPORT_DIR = backbones_pipeline.EXPORT_DIR
FIRMWARE_DIR = Path(__file__).resolve().parent / "src_inference_embedding_fusion"

AUDIO_SPECTROGRAM_BINS = audio_pipeline.FFT_LENGTH // 2 + 1
export_utils.AUDIO_SPECTROGRAM_BINS = AUDIO_SPECTROGRAM_BINS
AUDIO_RAW_FRAMES = (audio_pipeline.TARGET_SAMPLES - audio_pipeline.FRAME_LENGTH) // audio_pipeline.FRAME_STEP + 1
EMBEDDING_DIM = 64


def build_self_test_vectors(imu_quant, audio_quant, imu_channel_mean, imu_channel_std, audio_bin_mean,
                             audio_bin_std, classes, samples_per_class=1):
    """Real, labeled validation windows quantized separately for the IMU and audio
    embedders. Firmware chains embedder -> embedder -> fusion head on these at boot,
    exercising the full multi-model pipeline (including the dequantize/requantize hop
    between the embedders and the fusion head) before live capture ever runs."""
    imu_paths, audio_paths, labels = discover_paired_windows(imu_pipeline.DATA_ROOT, audio_pipeline.DATA_ROOT)
    x_imu = np.stack([load_imu_window(p) for p in imu_paths])
    x_audio_waveforms = np.stack([load_audio_waveform(p) for p in audio_paths])
    x_audio = audio_pipeline.compute_log_mel_spectrograms(x_audio_waveforms)  # (N, 198, 40, 1) native

    label_encoder = LabelEncoder()
    label_encoder.classes_ = np.asarray(classes)
    y_encoded = label_encoder.transform(labels)

    _, val_idx = train_test_split(np.arange(len(labels)), test_size=0.2, stratify=y_encoded, random_state=42)

    chosen_indices = []
    seen_classes = set()
    for idx in val_idx:
        class_index = int(y_encoded[idx])
        if class_index in seen_classes:
            continue
        seen_classes.add(class_index)
        chosen_indices.append(idx)
        if len(seen_classes) >= len(classes) * samples_per_class:
            break

    vectors = []
    for idx in chosen_indices:
        imu_normalized = (x_imu[idx] - imu_channel_mean) / imu_channel_std
        imu_q = np.round(imu_normalized / imu_quant["input_scale"] + imu_quant["input_zero_point"])
        imu_q = np.clip(imu_q, -128, 127).astype(np.int8)

        audio_normalized = (x_audio[idx] - audio_bin_mean) / audio_bin_std
        audio_q = np.round(audio_normalized / audio_quant["input_scale"] + audio_quant["input_zero_point"])
        audio_q = np.clip(audio_q, -128, 127).astype(np.int8)

        vectors.append((imu_q, audio_q, int(y_encoded[idx])))
    return vectors


def write_test_vectors_header(output_path: Path, vectors):
    blocks = []
    for i, (imu_q, audio_q, label) in enumerate(vectors):
        for tag, arr in (("IMU", imu_q), ("AUDIO", audio_q)):
            flat = arr.flatten()
            lines = []
            for j in range(0, len(flat), 20):
                lines.append("    " + ", ".join(str(int(v)) for v in flat[j : j + 20]) + ",")
            body = "\n".join(lines)
            blocks.append(f"const int8_t TEST_VECTOR_{i}_{tag}_DATA[{len(flat)}] = {{\n{body}\n}};\n")
        blocks.append(f"const int TEST_VECTOR_{i}_LABEL = {label};\n")

    imu_pointer_list = ",\n    ".join(f"TEST_VECTOR_{i}_IMU_DATA" for i in range(len(vectors)))
    audio_pointer_list = ",\n    ".join(f"TEST_VECTOR_{i}_AUDIO_DATA" for i in range(len(vectors)))
    label_list = ", ".join(str(label) for _, _, label in vectors)

    content = f"""// Auto-generated by export_embedding_fusion_model.py -- do not edit by hand.
// Real, labeled validation windows, pre-normalized and quantized separately for the IMU
// and audio embedders exactly like the live capture pipeline would. Used by
// runSelfTest() in main.cpp.
#pragma once

#include <cstdint>

constexpr int NUM_TEST_VECTORS = {len(vectors)};

{"".join(blocks)}
const int8_t *const TEST_VECTOR_IMU[NUM_TEST_VECTORS] = {{
    {imu_pointer_list}
}};
const int8_t *const TEST_VECTOR_AUDIO[NUM_TEST_VECTORS] = {{
    {audio_pointer_list}
}};
const int TEST_VECTOR_LABELS[NUM_TEST_VECTORS] = {{{label_list}}};
"""
    output_path.write_text(content)


def write_model_settings_header(
    output_path: Path,
    classes,
    imu_channel_mean, imu_channel_std,
    audio_bin_mean, audio_bin_std,
    mel_filterbank, hann_window,
    imu_quant, audio_quant, fusion_quant,
):
    class_name_array = ",\n    ".join(f'"{name}"' for name in classes)

    content = f"""// Auto-generated by export_embedding_fusion_model.py -- do not edit by hand.
#pragma once

// --- Class labels (index order matches the fusion head's output tensor) ---
constexpr int NUM_CLASSES = {len(classes)};
const char *const CLASS_NAMES[NUM_CLASSES] = {{
    {class_name_array}
}};

// --- IMU window dimensions ---
constexpr int IMU_WINDOW_LENGTH = {imu_pipeline.WINDOW_LENGTH};
constexpr int IMU_CHANNELS = {len(imu_pipeline.CHANNEL_COLUMNS)};

// --- Audio capture / STFT parameters -- native (unresampled) spectrogram shape ---
constexpr int AUDIO_SAMPLE_RATE = {audio_pipeline.SAMPLE_RATE};
constexpr int AUDIO_TARGET_SAMPLES = {audio_pipeline.TARGET_SAMPLES};
constexpr int AUDIO_FRAME_LENGTH = {audio_pipeline.FRAME_LENGTH};
constexpr int AUDIO_FRAME_STEP = {audio_pipeline.FRAME_STEP};
constexpr int AUDIO_FFT_LENGTH = {audio_pipeline.FFT_LENGTH};
constexpr int AUDIO_SPECTROGRAM_BINS = {AUDIO_SPECTROGRAM_BINS};
constexpr int AUDIO_RAW_FRAMES = {AUDIO_RAW_FRAMES};
constexpr int AUDIO_MEL_BINS = {audio_pipeline.NUM_MEL_BINS};

// --- Embedding-level fusion: each backbone's 64-d penultimate features, concatenated
// into a 128-d vector fed to a small trained fusion head. ---
constexpr int EMBEDDING_DIM = {EMBEDDING_DIM};
constexpr int FUSED_EMBEDDING_DIM = EMBEDDING_DIM * 2;

// --- IMU embedder quantization (input: raw window; output: 64-d embedding) ---
constexpr float IMU_INPUT_SCALE = {imu_quant["input_scale"]:.10g}f;
constexpr int IMU_INPUT_ZERO_POINT = {imu_quant["input_zero_point"]};
constexpr float IMU_OUTPUT_SCALE = {imu_quant["output_scale"]:.10g}f;
constexpr int IMU_OUTPUT_ZERO_POINT = {imu_quant["output_zero_point"]};

// --- Audio embedder quantization (input: raw spectrogram; output: 64-d embedding) ---
constexpr float AUDIO_INPUT_SCALE = {audio_quant["input_scale"]:.10g}f;
constexpr int AUDIO_INPUT_ZERO_POINT = {audio_quant["input_zero_point"]};
constexpr float AUDIO_OUTPUT_SCALE = {audio_quant["output_scale"]:.10g}f;
constexpr int AUDIO_OUTPUT_ZERO_POINT = {audio_quant["output_zero_point"]};

// --- Fusion head quantization (input: concatenated 128-d embedding; output: class scores).
// Firmware must dequantize both embedder outputs with their OWN output scale/zero_point,
// concatenate as float, then requantize with THESE before feeding the fusion head -- the
// three models were quantized independently, so there's no shared scale to reuse. ---
constexpr float FUSION_INPUT_SCALE = {fusion_quant["input_scale"]:.10g}f;
constexpr int FUSION_INPUT_ZERO_POINT = {fusion_quant["input_zero_point"]};
constexpr float FUSION_OUTPUT_SCALE = {fusion_quant["output_scale"]:.10g}f;
constexpr int FUSION_OUTPUT_ZERO_POINT = {fusion_quant["output_zero_point"]};

// --- IMU per-channel normalization stats from the training split ({imu_pipeline.CHANNEL_COLUMNS}) ---
{export_utils.format_c_array("IMU_CHANNEL_MEAN", imu_channel_mean, "float")}
{export_utils.format_c_array("IMU_CHANNEL_STD", imu_channel_std, "float")}

// --- Audio per-mel-bin normalization stats from the training split ---
{export_utils.format_c_array("AUDIO_BIN_MEAN", audio_bin_mean, "float")}
{export_utils.format_c_array("AUDIO_BIN_STD", audio_bin_std, "float")}

// --- Precomputed mel filterbank matrix, shape [AUDIO_SPECTROGRAM_BINS][AUDIO_MEL_BINS] ---
{export_utils.format_c_array("MEL_FILTERBANK", mel_filterbank, "float")}

// --- Periodic Hann window (length AUDIO_FRAME_LENGTH) ---
{export_utils.format_c_array("HANN_WINDOW", hann_window, "float")}
"""
    output_path.write_text(content)


def main():
    backbones_export = np.load(EXPORT_DIR / "fusion_backbones_small_export_data.npz", allow_pickle=True)
    embedding_export = np.load(EXPORT_DIR / "embedding_fusion_small_export_data.npz", allow_pickle=True)

    imu_channel_mean = backbones_export["imu_channel_mean"]
    imu_channel_std = backbones_export["imu_channel_std"]
    audio_bin_mean = backbones_export["audio_bin_mean"]
    audio_bin_std = backbones_export["audio_bin_std"]
    classes = backbones_export["classes"]
    imu_representative_samples = backbones_export["imu_representative_samples"]
    audio_representative_samples = backbones_export["audio_representative_samples"]
    fused_representative_samples = embedding_export["fused_representative_samples"]

    imu_model = tf.keras.models.load_model(EXPORT_DIR / "imu_backbone_small.keras")
    audio_model = tf.keras.models.load_model(EXPORT_DIR / "audio_backbone_small.keras")
    fusion_model = tf.keras.models.load_model(EXPORT_DIR / "fusion_head_small.keras")

    imu_embedder = get_embedding_model(imu_model)
    audio_embedder = get_embedding_model(audio_model)
    # get_embedding_model slices trained layers into a fresh Sequential (see its own
    # comment on why -- model.input/.output introspection doesn't survive save/reload in
    # this Keras version either). That fresh Sequential has no known input shape until
    # something builds it, which TFLiteConverter requires up front rather than inferring
    # from a .predict() call the way plain Python usage would.
    imu_embedder.build(input_shape=imu_model.input_shape)
    audio_embedder.build(input_shape=audio_model.input_shape)

    print("Converting IMU embedder to int8 TFLite...")
    imu_tflite = export_utils.convert_to_int8_tflite(imu_embedder, imu_representative_samples)
    imu_quant = export_utils.get_io_quantization(imu_tflite)
    print(f"  size={len(imu_tflite)} bytes, input={imu_quant['input_scale']}/{imu_quant['input_zero_point']}, "
          f"output={imu_quant['output_scale']}/{imu_quant['output_zero_point']}")

    print("Converting audio embedder to int8 TFLite...")
    audio_tflite = export_utils.convert_to_int8_tflite(audio_embedder, audio_representative_samples)
    audio_quant = export_utils.get_io_quantization(audio_tflite)
    print(f"  size={len(audio_tflite)} bytes, input={audio_quant['input_scale']}/{audio_quant['input_zero_point']}, "
          f"output={audio_quant['output_scale']}/{audio_quant['output_zero_point']}")

    print("Converting fusion head to int8 TFLite...")
    fusion_tflite = export_utils.convert_to_int8_tflite(fusion_model, fused_representative_samples)
    fusion_quant = export_utils.get_io_quantization(fusion_tflite)
    print(f"  size={len(fusion_tflite)} bytes, input={fusion_quant['input_scale']}/{fusion_quant['input_zero_point']}, "
          f"output={fusion_quant['output_scale']}/{fusion_quant['output_zero_point']}")

    mel_filterbank = export_utils.compute_mel_filterbank()
    hann_window = export_utils.compute_hann_window()

    FIRMWARE_DIR.mkdir(exist_ok=True)
    (EXPORT_DIR / "embedding_fusion_imu_int8.tflite").write_bytes(imu_tflite)
    (EXPORT_DIR / "embedding_fusion_audio_int8.tflite").write_bytes(audio_tflite)
    (EXPORT_DIR / "embedding_fusion_head_int8.tflite").write_bytes(fusion_tflite)

    export_utils.write_model_data_header(imu_tflite, FIRMWARE_DIR / "imu_model_data.h", "g_imu_model_data")
    export_utils.write_model_data_header(audio_tflite, FIRMWARE_DIR / "audio_model_data.h", "g_audio_model_data")
    export_utils.write_model_data_header(fusion_tflite, FIRMWARE_DIR / "fusion_model_data.h", "g_fusion_model_data")

    write_model_settings_header(
        FIRMWARE_DIR / "model_settings.h",
        classes,
        imu_channel_mean, imu_channel_std,
        audio_bin_mean, audio_bin_std,
        mel_filterbank, hann_window,
        imu_quant, audio_quant, fusion_quant,
    )
    print(f"Wrote headers to {FIRMWARE_DIR}")

    print("Building self-test vectors...")
    vectors = build_self_test_vectors(
        imu_quant, audio_quant, imu_channel_mean, imu_channel_std, audio_bin_mean, audio_bin_std, classes
    )
    write_test_vectors_header(FIRMWARE_DIR / "test_vectors.h", vectors)
    print(f"Wrote test_vectors.h ({len(vectors)} vectors)")


if __name__ == "__main__":
    main()
